name: Contract tests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      author:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'PR author'
        # Default value if no value is explicitly provided
        default: 'Sonu Puthukudi'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      server:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'server (preprod/staging/dev/local)'
        # Default value if no value is explicitly provided
        default: 'local'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up environment
      run: |
          cd ../
          npm install
    - name: Run tests
      run: |
          cd ../
          npm run test
