name: Contract tests

on:
  workflow_dispatch:
    inputs:
      author:
        description: 'PR author'
        default: 'Sonu Puthukudi'
        required: true
        type: string
      server:
        description: 'server (preprod/staging/dev/local)'
        default: 'local'
        required: true
        type: string

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up environment
      run: |
          npm install
    - name: Run tests
      run: |
          npm run test
